home:
    path: /home
    controller: App\Controller\HomeController::Home
shortcut:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    default:
       path: 'home' 